# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef1f8eccdd89d187929426cdeab5afa3c71a5c05a43167a6d99ba965cf5e502360f93d341534f84f17cb2ff66985e53fa605773a6ed68b5ae6f13ca94b6e3b8d

test:
  secret_key_base: 279ed33fc21a409eeb3a17cdd71cd09953115fc5e554b62630dc5946cba1836c4e41218c87048195404acc5cb889ec8c19fe18a23686920c49f48e319c7be8df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
